import { Button, Card, CardContent, Stack, TextField, Typography } from '@mui/material'
import { useEffect, useState } from 'react'
import { ClientShell } from './components/application-shell'
import { RouterButtonLink } from './components/router-button-link'
import { LoadingState, PageHeader, StatusNotice } from './components/ui'
import { addPostComment, deletePostComment, getPostDetail, setPostLike, type PostDetail } from './social'

export function PostDetailPage({ accessToken, onSignOut, postId }: { accessToken: string; onSignOut: () => void; postId: string }) {
  const [detail, setDetail] = useState<PostDetail | null>(null); const [comment, setComment] = useState(''); const [error, setError] = useState<string | null>(null)
  const load = () => { void getPostDetail(accessToken, postId).then(setDetail).catch(() => setError('Não foi possível carregar a publicação.')) }; useEffect(load, [accessToken, postId])
  async function like() { if (!detail) return; try { setDetail(await setPostLike(accessToken, postId, !detail.liked_by_viewer)) } catch { setError('Não foi possível atualizar a curtida.') } }
  async function publish() { try { await addPostComment(accessToken, postId, comment); setComment(''); load() } catch { setError('Não foi possível publicar o comentário.') } }
  async function remove(id: string) { try { await deletePostComment(accessToken, id); load() } catch { setError('Não foi possível excluir o comentário.') } }
  return <ClientShell onSignOut={onSignOut} showClientNavigation><Stack spacing={3} sx={{ maxWidth: 760 }}><PageHeader action={<RouterButtonLink to="/perfil" variant="outlined">Voltar ao perfil</RouterButtonLink>} eyebrow="Publicação" title="Detalhes da publicação" />{error && <StatusNotice severity="error">{error}</StatusNotice>}{!detail ? <LoadingState label="Carregando publicação" /> : <><Card><CardContent><Stack spacing={2}><Typography component="h2" variant="h3">{detail.author.nickname || detail.author.name}</Typography><Typography sx={{ whiteSpace: 'pre-wrap' }}>{detail.post.content}</Typography><Button onClick={() => void like()} sx={{ alignSelf: 'flex-start' }} variant="outlined">{detail.liked_by_viewer ? 'Descurtir' : 'Curtir'} · {detail.like_count}</Button></Stack></CardContent></Card><Typography component="h2" variant="h3">Comentários</Typography><Card component="form" onSubmit={(event) => { event.preventDefault(); void publish() }}><CardContent><Stack spacing={1.5}><TextField fullWidth inputProps={{ maxLength: 2000 }} label="Adicionar comentário" multiline minRows={2} onChange={(event) => setComment(event.target.value)} value={comment} /><Button disabled={!comment.trim()} type="submit" variant="contained">Comentar</Button></Stack></CardContent></Card>{detail.comments.map((item) => <Card key={item.id}><CardContent><Stack spacing={1}><Typography variant="subtitle2">{item.author.nickname || item.author.name}</Typography><Typography sx={{ whiteSpace: 'pre-wrap' }}>{item.content}</Typography>{item.is_own && <Button color="error" onClick={() => void remove(item.id)} size="small" sx={{ alignSelf: 'flex-start' }} variant="text">Excluir meu comentário</Button>}</Stack></CardContent></Card>)}</>}</Stack></ClientShell>
}
