import { Button, Card, CardContent, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useEffect, useState } from 'react'
import { ClientShell } from './components/application-shell'
import { EmptyState, LoadingState, PageHeader, StatusNotice } from './components/ui'
import { createProgressUpdate, deleteProgressUpdate, getProgressFeed, type ProgressUpdate } from './progress'

export function ProgressPage({ accessToken, onSignOut }: { accessToken: string; onSignOut: () => void }) {
  const [updates, setUpdates] = useState<ProgressUpdate[] | null>(null); const [content, setContent] = useState(''); const [visibility, setVisibility] = useState<'private' | 'shared'>('private'); const [error, setError] = useState<string | null>(null)
  const load = () => { setUpdates(null); void getProgressFeed(accessToken).then(setUpdates).catch((e: unknown) => { setError(e instanceof Error ? e.message : 'Não foi possível carregar suas atualizações.'); setUpdates([]) }) }
  useEffect(load, [accessToken])
  async function publish() { try { const update = await createProgressUpdate(accessToken, content, visibility); setUpdates((items) => [update, ...(items ?? [])]); setContent('') } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível publicar sua atualização.') } }
  async function remove(id: string) { try { await deleteProgressUpdate(accessToken, id); setUpdates((items) => items?.filter((item) => item.id !== id) ?? []) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível excluir sua atualização.') } }
  if (!updates) return <ClientShell onSignOut={onSignOut} showClientNavigation><LoadingState label="Carregando seu progresso" /></ClientShell>
  return <ClientShell onSignOut={onSignOut} showClientNavigation><Stack spacing={3} sx={{ maxWidth: 760, minWidth: 0 }}><PageHeader eyebrow="Meu progresso" title="Compartilhe seu avanço" description="Registre uma conquista. Compartilhar é opcional e suas informações de saúde, pagamento ou acesso não são incluídas automaticamente." />{error && <StatusNotice severity="error">{error}</StatusNotice>}<Card component="form" onSubmit={(e) => { e.preventDefault(); void publish() }}><CardContent><Stack spacing={2}><TextField fullWidth label="Sua atualização" multiline minRows={3} value={content} onChange={(e) => setContent(e.target.value)} /><FormControl fullWidth><InputLabel id="visibility-label">Visibilidade</InputLabel><Select label="Visibilidade" labelId="visibility-label" value={visibility} onChange={(e) => setVisibility(e.target.value as 'private' | 'shared')}><MenuItem value="private">Somente eu</MenuItem><MenuItem value="shared">Compartilhar com clientes ativos</MenuItem></Select></FormControl><Typography color="text.secondary" variant="body2">Não publique dados de saúde, pagamento, credenciais, presença ou frequência.</Typography><Button disabled={!content.trim()} type="submit" variant="contained">Publicar atualização</Button></Stack></CardContent></Card>{updates.length === 0 ? <EmptyState title="Nenhuma atualização ainda" description="Registre seu progresso quando quiser. Por padrão, ele fica visível somente para você." /> : updates.map((item) => <Card component="article" key={item.id}><CardContent><Stack spacing={1.25}><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between' }}><Typography component="h2" variant="h4">{item.author_name}</Typography><Typography color="text.secondary" variant="body2">{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.created_at))}</Typography></Stack><Typography sx={{ overflowWrap: 'anywhere', whiteSpace: 'pre-wrap' }}>{item.content}</Typography>{item.is_own && item.visibility === 'private' && <StatusNotice severity="info">Visível somente para você</StatusNotice>}{item.is_own && item.moderation_status === 'hidden' && <StatusNotice severity="error">Sua atualização foi ocultada: {item.moderation_reason}</StatusNotice>}{item.is_own && <Button onClick={() => void remove(item.id)} size="small" sx={{ alignSelf: 'flex-start' }} variant="text">Excluir minha atualização</Button>}</Stack></CardContent></Card>)}</Stack></ClientShell>
}
